export const USER_ACTION_TYPES = {
    ADD_ITEMS_TO_CART: "ADD_ITEMS_TO_CART",
    REMOVE_ITEMS_FROM_CART:"REMOVE_ITEMS_FROM_CART",
    INCREMENT_ITEM_FROM_CART: "INCREMENT_ITEM_FROM_CART",
    DECREMENT_ITEM_FROM_CART: "DECREMENT_ITEM_FROM_CART"
}